-- Generated by Themeport from the reviewed system theme catalog.
local function apply_theme()
  require("base16-colorscheme").setup({
    base00 = "{{ background }}",
    base01 = "{{ color0 }}",
    base02 = "{{ color8 }}",
    base03 = "{{ muted }}",
    base04 = "{{ dark_foreground }}",
    base05 = "{{ foreground }}",
    base06 = "{{ light_foreground }}",
    base07 = "{{ bright_foreground }}",
    base08 = "{{ red }}",
    base09 = "{{ orange }}",
    base0A = "{{ yellow }}",
    base0B = "{{ green }}",
    base0C = "{{ cyan }}",
    base0D = "{{ blue }}",
    base0E = "{{ magenta }}",
    base0F = "{{ brown }}",
  })

  vim.api.nvim_set_hl(0, "Visual", {
    bg = "{{ selection_background }}",
    fg = "{{ selection_foreground }}",
    bold = true,
  })
  vim.api.nvim_set_hl(0, "StatusLine", {
    bg = "{{ accent }}",
    fg = "{{ background }}",
  })
  vim.api.nvim_set_hl(0, "LineNr", { fg = "{{ muted }}" })
  vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "{{ accent }}", bold = true })
  vim.api.nvim_set_hl(0, "Statement", { fg = "{{ accent }}", bold = true })
  vim.api.nvim_set_hl(0, "Keyword", { link = "Statement" })
  vim.api.nvim_set_hl(0, "Repeat", { link = "Statement" })
  vim.api.nvim_set_hl(0, "Conditional", { link = "Statement" })
  vim.api.nvim_set_hl(0, "Function", { fg = "{{ blue }}", bold = true })
  vim.api.nvim_set_hl(0, "Macro", { fg = "{{ cyan }}", italic = true })
  vim.api.nvim_set_hl(0, "@function.macro", { link = "Macro" })
  vim.api.nvim_set_hl(0, "Type", { fg = "{{ green }}", bold = true, italic = true })
  vim.api.nvim_set_hl(0, "Structure", { link = "Type" })
  vim.api.nvim_set_hl(0, "String", { fg = "{{ green }}", italic = true })
  vim.api.nvim_set_hl(0, "Operator", { fg = "{{ foreground }}" })
  vim.api.nvim_set_hl(0, "Delimiter", { fg = "{{ foreground }}" })
  vim.api.nvim_set_hl(0, "@punctuation.bracket", { link = "Delimiter" })
  vim.api.nvim_set_hl(0, "@punctuation.delimiter", { link = "Delimiter" })
  vim.api.nvim_set_hl(0, "Comment", { fg = "{{ muted }}", italic = true })
end

local function install_watcher()
  if _G._themeport_theme_watcher then
    return
  end

  local current_file_path = vim.fn.stdpath("config") .. "/lua/plugins/dankcolors.lua"
  local uv = vim.uv or vim.loop
  local watcher = uv.new_fs_event()
  local timer = uv.new_timer()

  local function watch()
    pcall(function()
      watcher:stop()
    end)
    pcall(function()
      watcher:start(current_file_path, {}, vim.schedule_wrap(function()
        timer:stop()
        timer:start(100, 0, vim.schedule_wrap(function()
          local ok, new_spec = pcall(dofile, current_file_path)
          if ok and new_spec and new_spec[1] and new_spec[1].config then
            new_spec[1].config()
            vim.notify("Themeport palette reloaded")
          end
          watch()
        end))
      end))
    end)
  end

  _G._themeport_theme_watcher = { watcher = watcher, timer = timer }
  watch()
end

return {
  {
    "RRethy/base16-nvim",
    priority = 1000,
    config = function()
      apply_theme()
      install_watcher()
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = apply_theme,
    },
  },
}
