[colors.primary]
background = "#14131e"
foreground = "#e0def4"

[colors.cursor]
text = "#14131e"
cursor = "#e0def4"

[colors.vi_mode_cursor]
text = "#14131e"
cursor = "#e0def4"

[colors.search.matches]
foreground = "#14131e"
background = "#f6c177"

[colors.search.focused_match]
foreground = "#14131e"
background = "#eb6f92"

[colors.footer_bar]
foreground = "#14131e"
background = "#e0def4"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black = "#14131e"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#31748f"
magenta = "#c4a7e7"
cyan = "#9ccfd8"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#31748f"
magenta = "#c4a7e7"
cyan = "#9ccfd8"
white = "#e0def4"
