-- Generated by Themeport from the reviewed system theme catalog.
local function apply_theme()
  require("base16-colorscheme").setup({
    base00 = "#1a1b26",
    base01 = "#1a1b26",
    base02 = "#414868",
    base03 = "#414868",
    base04 = "#565f89",
    base05 = "#a9b1d6",
    base06 = "#b4bee6",
    base07 = "#c0caf5",
    base08 = "#f7768e",
    base09 = "#eb927b",
    base0A = "#e0af68",
    base0B = "#9ece6a",
    base0C = "#449dab",
    base0D = "#7aa2f7",
    base0E = "#ad8ee6",
    base0F = "#75493d",
  })

  vim.api.nvim_set_hl(0, "Visual", {
    bg = "#292e42",
    fg = "#c0caf5",
    bold = true,
  })
  vim.api.nvim_set_hl(0, "StatusLine", {
    bg = "#7aa2f7",
    fg = "#1a1b26",
  })
  vim.api.nvim_set_hl(0, "LineNr", { fg = "#414868" })
  vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#7aa2f7", bold = true })
  vim.api.nvim_set_hl(0, "Statement", { fg = "#7aa2f7", bold = true })
  vim.api.nvim_set_hl(0, "Keyword", { link = "Statement" })
  vim.api.nvim_set_hl(0, "Repeat", { link = "Statement" })
  vim.api.nvim_set_hl(0, "Conditional", { link = "Statement" })
  vim.api.nvim_set_hl(0, "Function", { fg = "#7aa2f7", bold = true })
  vim.api.nvim_set_hl(0, "Macro", { fg = "#449dab", italic = true })
  vim.api.nvim_set_hl(0, "@function.macro", { link = "Macro" })
  vim.api.nvim_set_hl(0, "Type", { fg = "#9ece6a", bold = true, italic = true })
  vim.api.nvim_set_hl(0, "Structure", { link = "Type" })
  vim.api.nvim_set_hl(0, "String", { fg = "#9ece6a", italic = true })
  vim.api.nvim_set_hl(0, "Operator", { fg = "#a9b1d6" })
  vim.api.nvim_set_hl(0, "Delimiter", { fg = "#a9b1d6" })
  vim.api.nvim_set_hl(0, "@punctuation.bracket", { link = "Delimiter" })
  vim.api.nvim_set_hl(0, "@punctuation.delimiter", { link = "Delimiter" })
  vim.api.nvim_set_hl(0, "Comment", { fg = "#414868", italic = true })
end

local function install_watcher()
  if _G._themeport_theme_watcher then
    return
  end

  local current_file_path = vim.fn.stdpath("config") .. "/lua/plugins/dankcolors.lua"
  local uv = vim.uv or vim.loop
  local watcher = uv.new_fs_event()
  local timer = uv.new_timer()

  local function watch()
    pcall(function()
      watcher:stop()
    end)
    pcall(function()
      watcher:start(current_file_path, {}, vim.schedule_wrap(function()
        timer:stop()
        timer:start(100, 0, vim.schedule_wrap(function()
          local ok, new_spec = pcall(dofile, current_file_path)
          if ok and new_spec and new_spec[1] and new_spec[1].config then
            new_spec[1].config()
            vim.notify("Themeport palette reloaded")
          end
          watch()
        end))
      end))
    end)
  end

  _G._themeport_theme_watcher = { watcher = watcher, timer = timer }
  watch()
end

return {
  {
    "RRethy/base16-nvim",
    priority = 1000,
    config = function()
      apply_theme()
      install_watcher()
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = apply_theme,
    },
  },
}
