{
  imports = [
    ../modules/nixos/apps.nix
    ../modules/nixos/desktop.nix
    ../modules/nixos/development.nix
    ../modules/nixos/fonts.nix
    ../modules/nixos/home.nix
    ../modules/nixos/gnome-integrations.nix
    ../modules/nixos/manifesto.nix
    ../modules/nixos/networking.nix
    ../modules/nixos/neovim.nix
    ../modules/nixos/nix.nix
    ../modules/nixos/reminders.nix
    ../modules/nixos/tmux.nix
    ../modules/nixos/users.nix
    ../modules/nixos/vicinae.nix
    ../modules/nixos/virtualisation.nix
  ];
}
