{
  imports = [
    ../modules/nixos/apps.nix
    ../modules/nixos/backups.nix
    ../modules/nixos/capture.nix
    ../modules/nixos/desktop.nix
    ../modules/nixos/development.nix
    ../modules/nixos/fonts.nix
    ../modules/nixos/home.nix
    ../modules/nixos/manifesto.nix
    ../modules/nixos/networking.nix
    ../modules/nixos/neovim.nix
    ../modules/nixos/niri.nix
    ../modules/nixos/niri-pip.nix
    ../modules/nixos/nix.nix
    ../modules/nixos/reminders.nix
    ../modules/nixos/system-actions.nix
    ../modules/nixos/themeport.nix
    ../modules/nixos/tmux.nix
    ../modules/nixos/users.nix
    ../modules/nixos/vicinae.nix
    ../modules/nixos/voice.nix
    ../modules/nixos/virtualisation.nix
    ../modules/nixos/workspace-modes.nix
  ];
}
