[meta]
version = 1
name = "Catppuccin Mocha"
description = "A fixed Catppuccin Mocha palette"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
accent = "#cba6f7"
accent_foreground = "#1e1e2e"
background = "#1e1e2e"
foreground = "#cdd6f4"
secondary_background = "#313244"
border = "#45475a"

[colors.main_window]
border = "#45475a"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "#45475a"

[colors.accents]
blue = "#89b4fa"
green = "#a6e3a1"
magenta = "#f5c2e7"
orange = "#fab387"
red = "#f38ba8"
yellow = "#f9e2af"
cyan = "#94e2d5"
purple = "#cba6f7"

[colors.shortcut]
border = "colors.core.border"

[colors.text]
default = "colors.core.foreground"
muted = "#a6adc8"
danger = "#f38ba8"
success = "#a6e3a1"
placeholder = "#7f849c"
selection = { background = "#cba6f7", foreground = "#1e1e2e" }

[colors.text.links]
default = "#89b4fa"
visited = "#cba6f7"

[colors.input]
border = "#45475a"
border_focus = "#cba6f7"
border_error = "#f38ba8"

[colors.button.primary]
background = "#313244"
foreground = "#cdd6f4"
focus = { outline = "colors.core.accent" }

[colors.list.item.hover]
foreground = "#f5e0dc"
secondary_foreground = "#cdd6f4"

[colors.list.item.selection]
background = "#45475a"
foreground = "#f5e0dc"
secondary_background = "#313244"
secondary_foreground = "#cdd6f4"

[colors.grid.item]
background = "#313244"
hover = { outline = "#cba6f7" }
selection = { outline = "#f5e0dc" }

[colors.scrollbars]
background = "#45475a"

[colors.loading]
bar = "#cba6f7"
spinner = "#cdd6f4"
