# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7cdf3e08-99fb-4ac5-9480-f0c6c662cbd2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7cdf3e08-99fb-4ac5-9480-f0c6c662cbd2".device = "/dev/disk/by-uuid/7cdf3e08-99fb-4ac5-9480-f0c6c662cbd2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6722-507A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
