# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1C1C1E"

# Main text color
theme[main_fg]="#FFFFFF"

# Title color for boxes
theme[title]="#FFFFFF"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7A7A7A"

# Background color of selected item in processes box
theme[selected_bg]="#808080"

# Foreground color of selected item in processes box
theme[selected_fg]="#7A7A7A"

# Color of inactive/disabled text
theme[inactive_fg]="#2C2C2E"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#FFFFFF"

# Background color of the percentage meters
theme[meter_bg]="#808080"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#FFFFFF"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#8A8A8A"
theme[mem_box]="#FFDD80"
theme[net_box]="#F2F2F2"
theme[proc_box]="#7A7A7A"

# Box divider line and small boxes line color
theme[div_line]="#2C2C2E"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#FFDD80"
theme[temp_mid]="#6A6A6A"
theme[temp_end]="#F2F2F2"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#F2F2F2"
theme[cpu_mid]="#7A7A7A"
theme[cpu_end]="#8A8A8A"

# Mem/Disk free meter
theme[free_start]="#8A8A8A"
theme[free_mid]="#7A7A7A"
theme[free_end]="#F2F2F2"

# Mem/Disk cached meter
theme[cached_start]="#7A7A7A"
theme[cached_mid]="#F2F2F2"
theme[cached_end]="#8A8A8A"

# Mem/Disk available meter
theme[available_start]="#6A6A6A"
theme[available_mid]="#F2F2F2"
theme[available_end]="#F2F2F2"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#FFDD80"
theme[used_mid]="#F2F2F2"
theme[used_end]="#7A7A7A"

# Download graph colors
theme[download_start]="#6A6A6A"
theme[download_mid]="#F2F2F2"
theme[download_end]="#F2F2F2"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#FFDD80"
theme[upload_mid]="#F2F2F2"
theme[upload_end]="#7A7A7A"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#F2F2F2"
theme[process_mid]="#7A7A7A"
theme[process_end]="#8A8A8A"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#1C1C1E"
theme[gradient_color_1]="#1C1C1E"
theme[gradient_color_2]="#808080"
theme[gradient_color_3]="#2C2C2E"
theme[gradient_color_4]="#2C2C2E"
theme[gradient_color_5]="#FFFFFF"
theme[gradient_color_6]="#FFFFFF"
theme[gradient_color_7]="#FFFFFF"
